/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as StaffPortalRouteImport } from './routes/staff-portal'
import { Route as StudentPortalRouteImport } from './routes/student-portal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPortalRoute = StaffPortalRouteImport.update({
  id: '/staff-portal',
  path: '/staff-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPortalRoute = StudentPortalRouteImport.update({
  id: '/student-portal',
  path: '/student-portal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/programmes': typeof ProgrammesRoute
  '/staff-portal': typeof StaffPortalRoute
  '/student-portal': typeof StudentPortalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/programmes': typeof ProgrammesRoute
  '/staff-portal': typeof StaffPortalRoute
  '/student-portal': typeof StudentPortalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/programmes': typeof ProgrammesRoute
  '/staff-portal': typeof StaffPortalRoute
  '/student-portal': typeof StudentPortalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/departments'
    | '/downloads'
    | '/faq'
    | '/gallery'
    | '/news'
    | '/programmes'
    | '/staff-portal'
    | '/student-portal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/departments'
    | '/downloads'
    | '/faq'
    | '/gallery'
    | '/news'
    | '/programmes'
    | '/staff-portal'
    | '/student-portal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/departments'
    | '/downloads'
    | '/faq'
    | '/gallery'
    | '/news'
    | '/programmes'
    | '/staff-portal'
    | '/student-portal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DownloadsRoute: typeof DownloadsRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  ProgrammesRoute: typeof ProgrammesRoute
  StaffPortalRoute: typeof StaffPortalRoute
  StudentPortalRoute: typeof StudentPortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-portal': {
      id: '/staff-portal'
      path: '/staff-portal'
      fullPath: '/staff-portal'
      preLoaderRoute: typeof StaffPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-portal': {
      id: '/student-portal'
      path: '/student-portal'
      fullPath: '/student-portal'
      preLoaderRoute: typeof StudentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  DownloadsRoute: DownloadsRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  ProgrammesRoute: ProgrammesRoute,
  StaffPortalRoute: StaffPortalRoute,
  StudentPortalRoute: StudentPortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
